version: '3.8'

services:
  db:
    image: postgres:13  # You can change this to the desired version
    restart: always
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      POSTGRES_DB: ${POSTGRES_DB}        # Database name
      POSTGRES_USER: ${POSTGRES_USER}      # Database user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Database password
    ports:
      - "5432:5432"            # Expose PostgreSQL on the specified port